[package]
name    = "worker_crate"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["DedicatedWorkerGlobalScope", "MessageEvent", "console", "Request", "RequestInit", "Response"] }

protocol-crate = { path = "../protocol-crate" }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
